"""good db

Revision ID: 59c220fb7b1b
Revises: 
Create Date: 2023-05-28 14:47:10.259628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c220fb7b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_book_title'), ['book_title'], unique=True)
        batch_op.create_index(batch_op.f('ix_book_id'), ['id'], unique=False)

    op.create_table('informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_name', sa.String(length=100), nullable=True),
    sa.Column('borrower_last_name', sa.String(length=100), nullable=True),
    sa.Column('borrowed_date', sa.DateTime(), nullable=True),
    sa.Column('is_rented', sa.Boolean(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_informations_borrowed_date'), ['borrowed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_informations_borrower_last_name'), ['borrower_last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_informations_borrower_name'), ['borrower_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_informations_is_rented'), ['is_rented'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_informations_is_rented'))
        batch_op.drop_index(batch_op.f('ix_informations_borrower_name'))
        batch_op.drop_index(batch_op.f('ix_informations_borrower_last_name'))
        batch_op.drop_index(batch_op.f('ix_informations_borrowed_date'))

    op.drop_table('informations')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_id'))
        batch_op.drop_index(batch_op.f('ix_book_book_title'))
        batch_op.drop_index(batch_op.f('ix_book_author'))

    op.drop_table('book')
    # ### end Alembic commands ###
